name: Docker Build for PRs

on:
  push:
    branches:
    - '!main'
  pull_request:
    branches:
    - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: |
        docker build --tag ${{ secrets.ACR_URL }}/levelupdevops:${{ github.sha }} .
